# Generated by Django 4.0.4 on 2022-05-18 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfar_comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wfar_comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
