# Generated by Django 4.0.4 on 2022-05-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfar',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
