# Generated by Django 4.0.4 on 2022-04-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveSmallIntegerField(default=1)),
                ('emp_no', models.CharField(max_length=25, unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email_address', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=200)),
                ('mname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200)),
                ('ext_name', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200)),
                ('subdivision', models.CharField(max_length=200, null=True)),
                ('barangay', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=20, unique=True)),
                ('specialization', models.CharField(max_length=200, null=True)),
                ('program', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('assignee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faculty')),
            ],
        ),
    ]
