# Generated by Django 4.0.4 on 2022-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wfar_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_picture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
