# Generated by Django 4.0.4 on 2022-05-27 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wfar_comment_created_at_wfar_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=1000)),
                ('type', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField()),
                ('faculty_registered_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_registered', to=settings.AUTH_USER_MODEL)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_owner', to=settings.AUTH_USER_MODEL)),
                ('wfar_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wfar_comment')),
                ('wfar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wfar')),
            ],
        ),
    ]
