# Generated by Django 4.0.4 on 2022-05-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wfar_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfar',
            name='week_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week_id', to='core.week'),
        ),
    ]
