# Generated by Django 4.0.4 on 2022-05-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_faculty_assignee_id'),
        ('core', '0002_semester_is_active'),
    ]

    operations = [
    ]
