# Generated by Django 4.0.4 on 2022-05-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_faculty_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_picture',
            field=models.ImageField(default='/avatar.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wfar',
            name='week_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_id', to='core.week'),
        ),
    ]
