# Generated by Django 4.0.4 on 2022-05-10 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_wfar_week_id'),
        ('core', '0003_faculty_profile_picture'),
    ]

    operations = [
    ]
