# Generated by Django 4.0.4 on 2022-06-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notification_faculty_registered_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='signature',
            field=models.ImageField(null=True, upload_to='signatures'),
        ),
    ]
