# Generated by Django 4.0.4 on 2022-06-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faculty_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='view_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
